name = 'PKB Theme'
license = 'MIT'
licenselink = 'https://github.com/stradichenko/PKB-theme/blob/main/LICENSE'
description = 'An easy to setup and use HUGO theme with academic and Personal Knowledge Base content in mind'

[author]
    name = "stradichenko"
    homepage = "https://krotanote.xyz/"

# Demo configuration
demosite = 'https://stradichenko.github.io/PKB-theme/'

# Taxonomy terms
tags = ['documentation', 'knowledge-base']
features = ['responsive', 'search', 'blog', 'PKB']

min_version = "0.136.0"
