baseURL      = "https://stradichenko.github.io/PKB-theme/"
languageCode = "en-us"
title        = "PKB-theme Demo"

# publish the site into ../docs for GitHub Pages
#publishDir = "docs"

[module]
  [[module.imports]]
    path = "github.com/stradichenko/PKB-theme"
    # version = "v1.0.0"  # optional pin once you have tags
    
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"

    [[module.imports.mounts]]
      source = "static" # “inside the theme repo, find static/images/profile.png”
      target = "static" # “inject it into my site’s

    [[module.imports.mounts]]
      source = "assets"
      target = "assets"

    [[module.imports.mounts]]
      source = "content"
      target = "content"

    [[module.imports.mounts]]
      source = "archetypes"
      target = "archetypes"